app-type: debian-package

build-image: dockerregistry.test.netflix.net:7002/engtools/newt-c-builder/xenial:latest

build-step:
  - >
    sudo apt-get update && sudo apt-get install -y
    cmake
    yasm
    chrpath
  - mkdir -p $(pwd)/newt_pkg/apps/transcoder/bin/svt-av1/
  - mkdir -p $(pwd)/newt_pkg/apps/transcoder/conf/svt-av1/
  - mkdir -p $(pwd)/newt_pkg/apps/transcoder/lib/svt-av1/
  - cd Build/linux && ./build.sh release
  - cp Bin/Release/SvtAv1EncApp $(pwd)/newt_pkg/apps/transcoder/bin/svt-av1/
  - cp Bin/Release/libSvtAv1Enc.so $(pwd)/newt_pkg/apps/transcoder/lib/svt-av1/
  - cp Config/Sample.cfg $(pwd)/newt_pkg/apps/transcoder/conf/svt-av1/
  - chmod +x $(pwd)/newt_pkg/apps/transcoder/bin/svt-av1/SvtAv1EncApp
  - cd $(pwd)/newt_pkg/apps/transcoder/bin/svt-av1/ && chrpath -r '/apps/transcoder/lib/svt-av1' SvtAv1EncApp


package-root: "newt_pkg"