image: Visual Studio 2017
configuration: Release

install:
    - git submodule update --init
    - appveyor DownloadFile http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe -FileName yasm.exe
    - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%
    - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_ASM_NASM_COMPILER="yasm.exe"

build:
  project: svt-av1.sln

artifacts:
    - path: bin\Release\*.*
      name: $(APPVEYOR_PROJECT_NAME)
    - path: bin\Release\**\*.exe
      name: $(APPVEYOR_PROJECT_NAME)-exe
    - path: bin\Release\**\*.lib
      name: $(APPVEYOR_PROJECT_NAME)-lib
    - path: \**\*svt-av1*.exe
      name: $(APPVEYOR_PROJECT_NAME)-exe
    - path: \**\*svt-av1*.lib
      name: $(APPVEYOR_PROJECT_NAME)-lib
