image: Visual Studio 2019
configuration: Release

install:
  - ps: |
      $wc = New-Object System.Net.WebClient
      $wc.DownloadFile('http://repo.msys2.org/distrib/msys2-x86_64-latest.tar.xz', "$PWD\msys2-base.tar.xz")
      $wc.DownloadFile((Invoke-RestMethod "https://www.powershellgallery.com/api/v2/Packages?`$filter=Id eq 'pscx' and IsLatestVersion").content.src, "$PWD\pscx.zip")
      Add-Type -assembly "System.IO.Compression.FileSystem"
      [System.IO.Compression.ZipFile]::ExtractToDirectory("$PWD\pscx.zip", "$PWD\pscx")
      Remove-Item -Recurse $PWD\pscx.zip, $PWD\pscx\_rels, $PWD\pscx\package
      powershell -noprofile -command {
          Import-Module $PWD\pscx\Pscx.psd1 -Force -Cmdlet Expand-Archive -Prefix 7za
          Expand-7zaArchive -Force -ShowProgress $PWD\msys2-base.tar.xz
          Remove-Item $PWD\msys2-base.tar.xz
          Expand-7zaArchive -Force -ShowProgress -OutputPath C:\ $PWD\msys2-base.tar
          Remove-Item $PWD\msys2-base.tar
      }
      Remove-Item -Recurse $PWD\pscx
  - set "PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%"
  - set MSYSTEM=MINGW64
  - set MSYS2_PATH_TYPE=inherit
  - bash -lc 'exit'
  - pacman -Sy --ask=20 --noconfirm --noprogressbar --needed mingw-w64-x86_64-yasm

  - cmake . -G "Visual Studio 16 2019" -A x64 -DBUILD_TESTING=ON

build:
  project: svt-av1.sln

artifacts:
  - path: bin\**\SvtAv1EncApp.exe
    name: $(APPVEYOR_PROJECT_NAME)
  - path: bin\**\SvtAv1DecApp.exe
    name: $(APPVEYOR_PROJECT_NAME)
  - path: bin\**\SvtAv1Enc.dll
    name: $(APPVEYOR_PROJECT_NAME)
  - path: bin\**\SvtAv1Dec.dll
    name: $(APPVEYOR_PROJECT_NAME)

deploy:
  - provider: GitHub
    artifact: $(APPVEYOR_PROJECT_NAME)
    auth_token:
      secure: 'sf0pQXlPI+X6LoAR8QUJB74jjzNxcLGOXI3H0nbxJq8llvGPG/TAUd87hq5iHZXo'
    prerelease: true
    on:
      appveyor_repo_tag: true
